server:
  port: 8000


#person:
#  lastName: zhanshan
#  age: 22
#  boss: false
#  idCard: 124559746
#  birthday: 2021/7/10
#  maps:
#    {k1: v1, k2: v2}
#  lists:
#    - lisi
#    - zhanMaZhi
#    - Master
#  dog:
#    name: haha
#    age: 2